version: '3.8'
services:
  web:
    build:
      context: .
    container_name: 'nuxt3-template'
    restart: always
    ports:
      - '3000:3000'
      - '24678:24678'
    command: 'yarn dev'
    volumes:
      - ./application:/app
      - /app/node_modules
